name: sambl
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  
  # The following adds firebase functionalities to the application
  cloud_firestore: "^0.7.0"
  intl: "^0.15.6"
  firebase_auth: "^0.5.11"
  cloud_functions: "^0.0.1"
  firebase_messaging: "^1.0.3"

  # The following adds Google authentication feature to the application
  google_sign_in: "^3.0.4"

  # The following adds packages used to implement redux architecture
  redux: "^3.0.0"
  flutter_redux: "^0.5.1"
  redux_thunk: "^0.2.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # The following adds the quiver library to the project
  quiver: '>=0.29.0 <0.30.0'

  # The following adds the haversine formula to the project, it allows calculation of distance between 2 points on a sphere
  haversine: "^1.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/sign_in_page_background.jpg
    - assets/images/home_page_background.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  
  fonts: 
    - family: Arual
      fonts:
        - asset: assets/fonts/Arual.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf
